/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.evmTI811X.host {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.evmTI811X.host; 1,0,0,1; 5-22-2012 16:26:09; /db/vtree/library/trees/ipc/ipc-h32/src/ xlibrary

 */

