/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY
 *
 */

metaonly module Platform inherits xdc.platform.IPlatform {

    config ti.platforms.generic.Platform.Instance CPU =
        ti.platforms.generic.Platform.create("CPU", {
            clockRate:      720.0,                                       
            catalogName:    "ti.catalog.arm.cortexa8",
            deviceName:     "OMAP3530",
            externalMemoryMap: 
           [          
                ["DDR", 
                     {
                        base: 0x80000000,                    
                        space: "code/data",
                        name: "DDR",
                        len: 0x800000,                    
                        access: "RWX",
                     }
                ],
                ["SHARED", 
                     {
                        base: 0x81000000,                    
                        space: "code/data",
                        name: "SHARED",
                        len: 0x800000,                    
                        access: "RWX",
                     }
                ],
           ],

    });
    
instance :
    
    override config string codeMemory  = "DDR";   
    override config string dataMemory  = "DDR";                                
    override config string stackMemory = "DDR";
    
}
/*
 *  @(#) ti.sdo.ipc.examples.platforms.omap3530.host; 1,0,0,1; 5-22-2012 16:27:21; /db/vtree/library/trees/ipc/ipc-h32/src/ xlibrary

 */

