/*
 *  Copyright 2012 by Texas Instruments Incorporated.
 *
 */

/*!
 * File generated by platform wizard. DO NOT MODIFY. 
 *
 */

package ti.sdo.ipc.examples.platforms.simVayu.eve2 {
    module Platform;
}

/*
 *  @(#) ti.sdo.ipc.examples.platforms.simVayu.eve2; 1,0,0,1; 5-22-2012 16:28:17; /db/vtree/library/trees/ipc/ipc-h32/src/ xlibrary

 */

